language: php
php:
  - '5.6'
  - '7.1'
  - '7.2'
  - nightly
script:
  - ./run_cold_start.php --rps=100 --users=1000 --time=20 1>/dev/null
  - ./run_cold_start.php --rps=100 --users=1000 --time=20 --random 1>/dev/null
  - ./run_modulo_resharding.php --keys=1000 --servers=4,5 1>/dev/null
  - ./run_modulo_resharding.php --keys=1000 --servers="1-10" 1>/dev/null
